# Generated by Django 2.1.7 on 2019-03-27 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Reseña')),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN')),
                ('sinopsis', models.TextField(blank=True, help_text='Ingrese la sinopsis', max_length=1000, null=True)),
                ('disponible', models.BooleanField(default=True, verbose_name='Estado actual')),
                ('autor', models.ForeignKey(help_text='Seleccione un autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Autor')),
                ('categoria', models.ManyToManyField(help_text='Seleccione una categoría', to='aplicacion.Categoria')),
                ('editorial', models.ForeignKey(help_text='Seleccione una editorial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Editorial')),
                ('idioma', models.ForeignKey(help_text='Seleccione un idioma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('encargado', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
    ]
