# Generated by Django 2.1.7 on 2019-04-01 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregarEjemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(blank=True, help_text='Ingrese nro. orden de compra', max_length=25, null=True)),
                ('cantidad_ejemplares', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad de ejemplares')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_ejemplares',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad de ejemplares'),
        ),
    ]
