# Generated by Django 2.1.7 on 2019-04-01 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20190401_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregarejemplar',
            name='cantidad_ejemplares',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de ejemplares'),
        ),
    ]
