# Generated by Django 2.1.7 on 2019-03-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20190324_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('encargado', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Reseña'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
