# Generated by Django 2.1.7 on 2019-04-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20190401_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar_libro',
            name='direccion_retiro',
            field=models.CharField(blank=True, help_text='Ingrese dirección de retiro', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar_libro',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Ingrese cliente que reserva el libro', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar_libro',
            name='retirar_en',
            field=models.CharField(blank=True, choices=[('v', 'Vendido'), ('d', 'Disponible'), ('r', 'Reservado')], default='t', help_text='Retirar en', max_length=1),
        ),
        migrations.AlterField(
            model_name='ejemplar_libro',
            name='estado',
            field=models.CharField(blank=True, choices=[('v', 'Vendido'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Seleccione estado', max_length=1),
        ),
    ]
